// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC04VK7x6g3obrT9snLW_bvqXAMMrNuL9w',
    appId: '1:114342389253:web:3b61dc8e8827a400195e6c',
    messagingSenderId: '114342389253',
    projectId: 'attendance-management-sy-f7493',
    authDomain: 'attendance-management-sy-f7493.firebaseapp.com',
    storageBucket: 'attendance-management-sy-f7493.appspot.com',
    measurementId: 'G-P8P8YHLFKD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDqhqbbfWdXJ3VX1xsC9UkjBXROT71HHWc',
    appId: '1:114342389253:android:f6436253aa11cc33195e6c',
    messagingSenderId: '114342389253',
    projectId: 'attendance-management-sy-f7493',
    storageBucket: 'attendance-management-sy-f7493.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAJwPRrf3tHHfU7UgcUs40Dj9559QdMX0Q',
    appId: '1:114342389253:ios:a087d5fc842c44ee195e6c',
    messagingSenderId: '114342389253',
    projectId: 'attendance-management-sy-f7493',
    storageBucket: 'attendance-management-sy-f7493.appspot.com',
    iosBundleId: 'com.example.attendenceManagementSystem',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAJwPRrf3tHHfU7UgcUs40Dj9559QdMX0Q',
    appId: '1:114342389253:ios:a087d5fc842c44ee195e6c',
    messagingSenderId: '114342389253',
    projectId: 'attendance-management-sy-f7493',
    storageBucket: 'attendance-management-sy-f7493.appspot.com',
    iosBundleId: 'com.example.attendenceManagementSystem',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC04VK7x6g3obrT9snLW_bvqXAMMrNuL9w',
    appId: '1:114342389253:web:4ca655165de8bd6f195e6c',
    messagingSenderId: '114342389253',
    projectId: 'attendance-management-sy-f7493',
    authDomain: 'attendance-management-sy-f7493.firebaseapp.com',
    storageBucket: 'attendance-management-sy-f7493.appspot.com',
    measurementId: 'G-YDQRNKKBGL',
  );
}
